"""initial_models_uuid

Revision ID: 5c68b115e065
Revises: 
Create Date: 2026-06-23 23:30:04.869164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c68b115e065'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgaos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('esfera', sa.String(length=50), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orgaos_cnpj'), 'orgaos', ['cnpj'], unique=True)
    op.create_index(op.f('ix_orgaos_id'), 'orgaos', ['id'], unique=False)
    op.create_table('licitacoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('orgao_id', sa.Uuid(), nullable=False),
    sa.Column('numero_controle', sa.String(length=100), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=False),
    sa.Column('modalidade', sa.String(length=100), nullable=True),
    sa.Column('situacao', sa.String(length=100), nullable=True),
    sa.Column('valor_estimado', sa.Float(), nullable=True),
    sa.Column('data_publicacao', sa.DateTime(), nullable=True),
    sa.Column('data_encerramento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgaos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacoes_id'), 'licitacoes', ['id'], unique=False)
    op.create_index(op.f('ix_licitacoes_numero_controle'), 'licitacoes', ['numero_controle'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licitacoes_numero_controle'), table_name='licitacoes')
    op.drop_index(op.f('ix_licitacoes_id'), table_name='licitacoes')
    op.drop_table('licitacoes')
    op.drop_index(op.f('ix_orgaos_id'), table_name='orgaos')
    op.drop_index(op.f('ix_orgaos_cnpj'), table_name='orgaos')
    op.drop_table('orgaos')
    # ### end Alembic commands ###
