"""Add fornecedores e contratos

Revision ID: 5ddb890e7cea
Revises: 73141de90f04
Create Date: 2026-06-27 20:55:55.724319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ddb890e7cea'
down_revision: Union[str, Sequence[str], None] = '73141de90f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ni', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('porte', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornecedores_id'), 'fornecedores', ['id'], unique=False)
    op.create_index(op.f('ix_fornecedores_ni'), 'fornecedores', ['ni'], unique=True)
    op.create_table('contratos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('licitacao_id', sa.Uuid(), nullable=False),
    sa.Column('fornecedor_id', sa.Uuid(), nullable=False),
    sa.Column('numero', sa.String(length=100), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('valor_contrato', sa.Float(), nullable=False),
    sa.Column('data_assinatura', sa.Date(), nullable=True),
    sa.Column('vigencia_inicio', sa.Date(), nullable=True),
    sa.Column('vigencia_fim', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['licitacao_id'], ['licitacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_id'), 'contratos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contratos_id'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_fornecedores_ni'), table_name='fornecedores')
    op.drop_index(op.f('ix_fornecedores_id'), table_name='fornecedores')
    op.drop_table('fornecedores')
    # ### end Alembic commands ###
