"""add itens arquivos e fases

Revision ID: 73141de90f04
Revises: 5c68b115e065
Create Date: 2026-06-24 00:35:06.444386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73141de90f04'
down_revision: Union[str, Sequence[str], None] = '5c68b115e065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arquivos_licitacao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('licitacao_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['licitacao_id'], ['licitacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arquivos_licitacao_id'), 'arquivos_licitacao', ['id'], unique=False)
    op.create_table('fases_licitacao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('licitacao_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['licitacao_id'], ['licitacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fases_licitacao_id'), 'fases_licitacao', ['id'], unique=False)
    op.create_table('itens_licitacao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('licitacao_id', sa.Uuid(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['licitacao_id'], ['licitacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_licitacao_id'), 'itens_licitacao', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_licitacao_id'), table_name='itens_licitacao')
    op.drop_table('itens_licitacao')
    op.drop_index(op.f('ix_fases_licitacao_id'), table_name='fases_licitacao')
    op.drop_table('fases_licitacao')
    op.drop_index(op.f('ix_arquivos_licitacao_id'), table_name='arquivos_licitacao')
    op.drop_table('arquivos_licitacao')
    # ### end Alembic commands ###
